### ISSUE TITLE
When I go to the link with code, The byte count was 0.

### ISSUE THREAD

**Issue by Fmbalbuena** [chunkybanana/do-stuff-online#4]
https://dso.surge.sh/#@WyJicmFpbmZ1Y2siLCIiLCIrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKy4iLCIiLCIiLCIiXQ==

**Comment by chunkybanana** [comment]
Fixed.
